### PR TITLE
Create Guide : Create a remote Repository

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by thesauravkarmakar — CHANGES_REQUESTED** [review]
1. **GUIDE TO CREATE A REMOTE REPOSITORY** - Format it as a  Headings and change the case to Title Case 
2. Don't need to add salutation like 'Hello' write the definition accordingly and refer to the format [Guide](https://github.com/thesauravkarmakar/GitHub101/blob/master/Guides/forking_a_repo.md) 
3. Keep the images aligned to the center

**Comment by thesauravkarmakar** [comment]
You did the same PR for two different things and now the older one is overwritten in the same PR issue. Fix the PR and create different PR for different issues.

**Comment by thesauravkarmakar** [comment]
@Pandz18  I have added some changes read those and fix accordingly.

**Comment by ghost** [comment]
Ok, I am sorry for the confusion , I have made two branches in the fork  and I had made two files so I deleted one in the main and the other in the new branch so as to make two separate PR , must've not worked , sorry , will change

**Comment by ghost** [comment]
I'll make a new RP with the changes, if it's ok

**Pull request closed without merging**
