### PR TITLE
Remote repo

### PR DESCRIPTION
**Pull request by Preetesh21**
Added the files for connecting local folder to a remote repository on GitHub for the issue #8 .

### CODE REVIEW

**Comment by thesauravkarmakar** [comment]
Until and unless it isn't never do PR. This time I'm ignoring.

**Comment by Preetesh21** [comment]
> Until and unless it isn't never do PR. This time I'm ignoring.

Sure I will take care of it next time and thanks for considering the PR.

**Comment by thesauravkarmakar** [comment]
@Preetesh21 I see you created a new file connecting-to-github-repository.md rather edit the changes with relevant screenshots in [linking_local_folders.md](https://github.com/thesauravkarmakar/GitHub101/blob/master/Guides/linking_local_folders.md)

**Comment by Preetesh21** [comment]
Yes.

**Pull request merged**
